# oelsmann24 Vertical Land Motion Pipeline



postprocess:
  task1:
    executable: "python3"
    script: "vlm_postprocess.py"
    options:
      - "nsamps"
      - "seed"
      - "baseyear"
      - "pyear_start"
      - "pyear_end"
      - "pyear_step"
      - "locationfile"
      - "chunksize"
      - "pipeline_id"      
    upload_input_data:
      - 'read_locationfile.py'
    copy_shared_data:
      - '$SHARED/location.lst'
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_data.pkl"
    local_total_files:
      - "%PIPELINE_ID%_localsl.nc"

